spring.application.name=job-tracker-backend
spring.mongodb.uri=mongodb+srv://job_tracker_db:phucnguyen123@job-tracker-cluster.npkzybm.mongodb.net/job_tracker_db?retryWrites=true&w=majority&appName=job-tracker-cluster
gemini.api.key=${GEMINI_API_KEY}
jwt.secret=day-la-mot-chuoi-bi-mat-rat-dai-va-kho-doan-cho-job-tracker-2026-thuc-tap
jwt.expiration=86400000
cloudinary.cloud-name=dpof0uvuf
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}